"""Canonical result models. Import from here rather than the submodule."""

from .analysis import (
    AnalysisMetadata,
    AnalysisWarning,
    AudioProperties,
    CompatibleKey,
    ConfidenceType,
    DJInterpretation,
    DJSegment,
    EngineInfo,
    KeyCandidate,
    KeyEstimate,
    LoudnessMeasurement,
    StageTiming,
    TempoCandidate,
    TempoEstimate,
    TempoRelation,
    TonalSegment,
    TrackAnalysis,
    TrackIdentity,
    WarningCode,
)

__all__ = [
    "AnalysisMetadata",
    "AnalysisWarning",
    "AudioProperties",
    "CompatibleKey",
    "ConfidenceType",
    "DJInterpretation",
    "DJSegment",
    "EngineInfo",
    "KeyCandidate",
    "KeyEstimate",
    "LoudnessMeasurement",
    "StageTiming",
    "TempoCandidate",
    "TempoEstimate",
    "TempoRelation",
    "TonalSegment",
    "TrackAnalysis",
    "TrackIdentity",
    "WarningCode",
]
